services:
  nginx:
    ports:
      - "${HTTP_PORT}:80"
    build:
      context: ./containers/nginx
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
        PROJECT_PREFIX: "$PROJECT_PREFIX"
    container_name: ${PROJECT_PREFIX}_webserver
    platform: linux/amd64
    depends_on:
      - mysql
    volumes:
      - ./../:/var/www/html
      - ./logs/nginx:/var/log/nginx
    links:
      - php
    restart: unless-stopped
    environment:
#      - APP_ENV=${APP_ENV}
      - PROJECT_PREFIX=${PROJECT_PREFIX}
    networks:
      default:
        aliases:
          - site.root

  php:
    platform: linux/amd64
    build:
      context: ./containers/php
      dockerfile: ./Dockerfile
      args:
        USER_ID: "$USER_ID"
        GROUP_ID: "$GROUP_ID"
    container_name: ${PROJECT_PREFIX}_php
    volumes:
      - ./../:/var/www/html
      - ./logs/php:/var/log/php
      - ./data/sessions:/var/www/sessions
    links:
      - mysql
#      - mailtrap
    restart: unless-stopped
    environment:
      APP_ENV: ${APP_ENV}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: ${MYSQL_HOST}
      PROJECT_PREFIX: "$PROJECT_PREFIX"
      PHP_IDE_CONFIG: serverName=Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    platform: linux/amd64
    build:
        context: ./containers/mysql
        dockerfile: ./Dockerfile
        args:
            USER_ID: ${USER_ID}
            GROUP_ID: ${GROUP_ID}
    container_name: ${PROJECT_PREFIX}_mysql
    ports:
      - "33060:3306"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./logs/mysql:/var/log/mysql
      - db-data:/var/lib/mysql
    restart: unless-stopped

#  mailtrap:
#    image: eaudeweb/mailtrap
#    platform: linux/amd64
#    container_name: ${PROJECT_PREFIX}_mailtrap
#    ports:
#      - "1080:80"

volumes:
  db-data:
